name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.6']
        julia-arch: [x64]
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Install dependencies
        env:
          PYTHON: ""
        run: pip install matplotlib; julia -e 'using Pkg; Pkg.add(url="https://github.com/byuflowlab/GeometricTools.jl"); Pkg.instantiate()';
      # - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
